### ISSUE TITLE
EmployeeProfile (seniority-calc-appgyver-srv) error 502

### ISSUE THREAD

**Issue by MattiaRedaelli** [SAP-samples/successfactors-extension-calculate-employee-seniority#11] opened 2022-04-27 14:48 UTC
Hello everyone,

I have a problem related to the EmployeeProfile (I don't know if it is linked to the other issuse that I have opened): when I try to access my link ***hana.ondemand.com/employee/EmployeeProfile I find the following error: "502 Bad Gateway : Registered endpoint failed to handle the request. ". 

[seniority-calc-appgyver-srv-2022-04-27 14_40_19.853+0000.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8573091/seniority-calc-appgyver-srv-2022-04-27.14_40_19.853%2B0000.txt)

Seeing the log I saw an error from the "ELIFECYCLE" code, which I have already tried to solve (for example I follow these steps https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err -code-elifecycle), but the problem doesn't change.

Thanks for support

**Comment by jmsrpp** [comment] 2022-04-27 22:23
@MattiaRedaelli - closing as this is being caused by the other bug. The error is because there are no employees in the HANA Cloud persistence. We provided some sample data to ideally address this but it may not have been deployed in your case.

**Closed as completed by jmsrpp** 2022-04-27 22:23 UTC
